import type ja from './ja'
const en: { [K in keyof typeof ja]: unknown } = {
  language: 'Language', country: 'Birth country', countryNames: { JP: 'Japan', KR: 'South Korea', US: 'United States' },
  entryTitle: 'BaZi Chart', profile: 'Profile', name: 'Name', gender: 'Gender', female: 'Female', male: 'Male', birthDate: 'Date of birth', birthDateTime: 'Date and time of birth', year: 'Year', month: 'Month', day: 'Day', birthTime: 'Time of birth', hour: 'Hour', minute: 'Minute', unknownTime: 'I don’t know the birth time',
  birthplace: 'Birthplace', searchLocation: 'Search city', locationAria: 'Search birthplace', locationPlaceholder: { JP: 'e.g. Tokyo, Shinjuku, Yokohama', KR: 'e.g. 서울, 강남, 수원', US: 'e.g. New York, Los Angeles, Chicago' }, candidates: 'Birthplace suggestions', noCandidates: 'No locations found', selectedLocation: 'Selected birthplace', useCorrection: 'Apply local time correction', submit: 'View BaZi Chart',
  errors: { year: 'Enter a four-digit year.', month: 'Enter a month from 1 to 12.', day: 'Enter a numeric day.', date: 'Enter a valid date for the selected month.', hour: 'Enter an hour from 0 to 23.', minute: 'Enter a minute from 0 to 59.', calculate: 'Could not calculate the entered date and time.' },
  back: 'Back to input', resultTitle: 'BaZi Chart', birthTimeUnknown: 'Birth time unknown', correctionOriginal: 'Recorded time', correction: 'Longitude correction', calculationTime: 'Calculation time', solarNotice: 'This date is a solar-term boundary, so the year or month pillar may depend on the birth time.', basicChart: 'Four Pillars',
  pillars: { 年柱: 'Year', 月柱: 'Month', 日柱: 'Day', 時柱: 'Hour' }, dayMaster: 'Day Master', tenGod: 'Ten Gods', twelveStagesTitle: 'Twelve Life Stages', hiddenStems: 'Hidden Stems', minuteUnit: ' min', roles: { residual: 'Residual', middle: 'Middle', main: 'Main' }, expandHidden: 'Show hidden stems', collapseHidden: 'Hide details', fortuneFlow: 'Fortune cycles', greatLuck: '10-year cycle', yearlyLuck: 'Yearly cycle', monthlyLuck: 'Monthly cycle',
  direction: { 順行: 'Forward', 逆行: 'Reverse' }, greatLuckList: '10-year cycles', yearlyLuckList: 'Yearly cycles', displayYear: 'Displayed year', previousYear: 'Previous year', nextYear: 'Next year', unknownStartAge: 'Start timing is approximate because the birth time is unknown.', startAge: 'Start', monthSuffix: ' mo', yearsSuffix: ' yrs', ageSeparator: ' / ', genderRequired: 'Select a gender to show the 10-year cycle.', ambiguousLuck: 'The birth time is unknown on a solar-term boundary, so the year and month pillars are uncertain.',
  tenGods: { 比肩: 'Peer', 劫財: 'Rob Wealth', 食神: 'Eating God', 傷官: 'Hurting Officer', 偏財: 'Indirect Wealth', 正財: 'Direct Wealth', 偏官: 'Seven Killings', 正官: 'Direct Officer', 偏印: 'Indirect Resource', 印綬: 'Direct Resource' },
  stages: { 長生: 'Birth', 沐浴: 'Bath', 冠帯: 'Youth', 建禄: 'Growth', 帝旺: 'Peak', 衰: 'Decline', 病: 'Illness', 死: 'Death', 墓: 'Tomb', 絶: 'Extinction', 胎: 'Conception', 養: 'Nurture' }, elements: { 木: 'Wood', 火: 'Fire', 土: 'Earth', 金: 'Metal', 水: 'Water' },
}
export default en as typeof ja
