export const FIVE_ELEMENTS: Record<string, { label: string; className: string; polarity?: '＋' | '−' }> = {
  甲: { label: '木', className: 'wood', polarity: '＋' },
  乙: { label: '木', className: 'wood', polarity: '−' },
  寅: { label: '木', className: 'wood' },
  卯: { label: '木', className: 'wood' },
  丙: { label: '火', className: 'fire', polarity: '＋' },
  丁: { label: '火', className: 'fire', polarity: '−' },
  巳: { label: '火', className: 'fire' },
  午: { label: '火', className: 'fire' },
  戊: { label: '土', className: 'earth', polarity: '＋' },
  己: { label: '土', className: 'earth', polarity: '−' },
  辰: { label: '土', className: 'earth' },
  戌: { label: '土', className: 'earth' },
  丑: { label: '土', className: 'earth' },
  未: { label: '土', className: 'earth' },
  庚: { label: '金', className: 'metal', polarity: '＋' },
  辛: { label: '金', className: 'metal', polarity: '−' },
  申: { label: '金', className: 'metal' },
  酉: { label: '金', className: 'metal' },
  壬: { label: '水', className: 'water', polarity: '＋' },
  癸: { label: '水', className: 'water', polarity: '−' },
  子: { label: '水', className: 'water' },
  亥: { label: '水', className: 'water' },
}
